services:
  etul-db:
    image: postgres:17
    container_name: "etul-db"
    hostname: etul-db
    restart: always
    command: ["postgres", "-p", "5425"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=etul
      - TZ=UTC
    volumes:
      - db-data-etul:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5425:5425"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -p 5425"]
      interval: 3s
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "5"
    networks:
      - internal

  pgadmin_etul:
    image: dpage/pgadmin4
    container_name: pgadmin_etul
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@example.com
      - PGADMIN_DEFAULT_PASSWORD=123456789
    ports:
      - "127.0.0.1:5055:80"
    depends_on:
      - etul-db
    networks:
      - internal

  etul:
    build:
      context: .
    container_name: etul
    env_file:
      - .env
    expose:
      - "2225"
    restart: unless-stopped
    networks:
      - internal

volumes:
  db-data-etul:
    driver: local
    external: false
    name: db-data-etul

networks:
  internal:
    name: internal
    driver: bridge
    external: false
